<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Branch;

class BranchSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $branches = [
            "Head Office",
            "Sta. Rosa",
            "Lucena",
            "Legaspi",
            "Batangas",
            "Naga",
            "Sta. Cruz",
            "LIPA",
            "SAN PABLO",
            "Daet",
            "MANDAUE (New)",
            "Lemery",
            "Nasugbu",
            "Balayan",
            "Bauan",
            "Calapan",
            "San Jose",
            "Tanauan",
            "Rosario",
            "SAN PEDRO",
            "Biñan",
            "Calamba",
            "Candelaria",
            "Los Baños (Closed)",
            "Gumaca (Closed)",
            "Boac",
            "Iriga",
            "Pili",
            "Goa",
            "Tabaco (Closed)",
            "Sorsogon",
            "Virac / Catanduanes (CLOSED)",
            "Masbate",
            "Polangui",
            "Daraga",
            "Caloocan",
            "SAFC SPARTA 1",
            "SAFC SPARTA 2",
            "SAFC SPARTA 3",
            "SAFC SPARTA 4",
            "SAU NORTH LUZON",
            "PINAMALAYAN",
            "ROXAS ORIENTAL MINDORO",
            "MAMBURAO",
            "STO TOMAS (Closed)",
            "SME BRANCH",
            "SAU AUTO LOANS - BATANGAS",
            "SAU AUTO LOANS - LAGUNA",
            "SAU AUTO LOANS - BICOL",
            "NAGA TRICYCLE UNIT",
            "LEGAZPI TRICYCLE UNIT",
            "SORSOGON TRICYCLE UNIT",
            "DAET TRICYCLE UNIT",
            "SHARED SERVICES UNIT",
            "SAU - AREA 3",
            "SAU - HEAD OFFICE",
            "AAMDD",
            "CABUYAO",
            "LUCENA TRICYCLE UNIT",
            "LIPA TRICYCLE UNIT",
            "SAN PABLO TRICYCLE UNIT",
            "BATANGAS TRICYCLE UNIT",
            "Mandaue (Old)",
            "PAGBILAO",
            "BACOOR",
            "LAS PIÑAS",
            "PLARIDEL",
            "STA. MARIA",
            "SALARY SPECIAL",
            "ANGELES",
            "FAIRVIEW",
            "VALENZUELA",
            "TAGUIG",
            "PARAÑAQUE",
            "PASAY",
            "BALANGA",
            "OLONGAPO",
            "GAPAN",
            "TARLAC",
            "URDANETA",
            "BRAND NEW CAR",
            "SAU 3 - REFINANCING",
            "ANTIPOLO",
            "CAINTA",
            "COMMONWEALTH",
            "MARIKINA",
            "SAN JUAN",
            "MANDALUYONG",
            "SARIAYA",
            "STO. TOMAS",
            "TIMOG QUEZON CITY",
            "SAN FERNANDO PAMPANGA",
            "MALABON",
            "RSO PAMPANGA",
            "IMUS",
            "MEYCAUAYAN",
            "SAN JOSE DEL MONTE",
            "TABACO",
            "BALIWAG",
            "SAU FSO CAVITE",
            "DASMARIÑAS CAVITE",
            "LIAN",
            "LOS BAÑOS New",
            "RSO BATANGAS",
            "DAGUPAN",
            "CABANATUAN",
            "MUNTINLUPA",
            "SAU FSO PAMPANGA",
            "SAU FSO PANGASINAN",
            "SAN FERNANDO LA UNION",
            "VIGAN",
            "TUGUEGARAO",
            "SANTIAGO",
            "GUMACA QUEZON",
            "SOLANO",
            "LAOAG",
            "BAGUIO",
            "MALOLOS",
            "SAU RENEWAL",
            "BRAND NEW CAR DIVISION",
            "TRUCK DIVISION",
            "REAL ESTATE DIVISION",
            "AGOO",
            "BRANCH FSO - BICOL",
            "MINDANAO AVENUE",
            "CEBU",
            "CAPAS",
            "PANIQUI",
            "BACOLOD",
            "DAVAO",
            "GENERAL SANTOS",
            "VIRAC",
            "ZAMBOANGA",
            "TAGAYTAY",
            "SAU SHARED",
            "COMPANY SHARED",
            "SAFC GROUP LOAN",
            "Special Accts A5 BAT",
            "Special Accts A5 BICOL",
            "Batangas Employee Salary Deduction",
            "Doctors / Truck Loan Special",
            "Head Office Employee Salary Deduction",
            "Intramuros",
            "Special Accts A5 LAG",
            "Lipa Employee Salary Loan",
            "Modified Business Loan Special",
            "MAKATI",
            "Rural Bank of Nasugbu Inc.",
            "Manila Branch",
            "Special Accts A5 HO",
            "San Pablo Employee Salary Loan",
            "Sta. Rosa Employee Salary Loan",
            "SAU NCR"
        ];

        foreach ($branches as $branch) {
            Branch::create([
                'branch_id' => mt_rand(1000, 9999),
                'branch_description' => $branch,
            ]);
        }
    }
}
